module.exports = {
  development: {
    dialect: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    username: 'root',
    password: 'senha_da_nasa',
    database: 'vuttr_development',
    operatorAliases: false,
    define: {
      timestamps: false,
      underscored: true,
      underscoredAll: true,
    },
  },
  test: {
    dialect: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    username: 'root',
    password: 'senha_da_nasa',
    database: 'vuttr_test',
    operatorAliases: false,
    define: {
      timestamps: false,
      underscored: true,
      underscoredAll: true,
    },
  },
  production: {
    use_env_variable: 'DATABASE_URL',
    dialect: 'mysql',
    host: 'sh4ob67ph9l80v61.cbetxkdyhwsb.us-east-1.rds.amazonaws.com',
    port: 3306,
    username: 'byr7mc4nup5w2ghu',
    password: 'iicfl77rfzff4cwv',
    database: 'j67buej374f7ve6z',
    operatorAliases: false,
    define: {
      timestamps: false,
      underscored: true,
      underscoredAll: true,
    },
  },
};
